### ISSUE TITLE
Create an account is broken

### ISSUE THREAD

**Issue by sammyjava** [LegumeFederation/peanutmine#10]
According to @piotyama who has been unsuccessful.

**Comment by adf-ncgr** [comment]
not sure if this is presents a good opportunity to look at #8 as well, but reminding you it is there

**Comment by sammyjava** [comment]
I'll get it fixed first since Paul wants to save his stuff. The single login thing can follow as the first thing to do when I finish getting all the mines updated.

**Comment by sammyjava** [comment]
Moved to mine-issues repo
