### ISSUE TITLE
can't add tags

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/peanutmine#3]
tried adding im:aspect:genomics (via New tag -> Add) but keeping getting : 
Oops!Adding tag failed.

I was able to Add the existing im:public tag to the template I imported, but then encountered this.
perhaps I'm not super enough?

**Comment by sammyjava** [comment]
PeanutMine doesn't have the tab categories implemented yet. Just SoyMine and LegumeMine so far.
