### ISSUE TITLE
example list for photosynthesis genes is broken in some way

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/peanutmine#6]
although the templated query for GO term (photosynthesis) -> genes seems to work fine, the saved example list "Cultivated peanut photosynthesis genes" has 0 genes.

**Comment by adf-ncgr** [comment]
I ran into this again. this time I created my own list "Photosynthesis genes 391 Genes" but I can't delete the broken one. @sammyjava will you take care of that when you get a chance. Then close this issue

**Comment by sammyjava** [comment]
Done.
