### ISSUE TITLE
enable google-based authentication

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/peanutmine#8]
starting with peanutmine to make @jd-campbell happy, but should propagate to other mines eventually. It works at https://bar.utoronto.ca/thalemine/begin.do

**Comment by sammyjava** [comment]
The mines all share the same code other than some mine-specific config stuff. All JSP and Java are communal, it's kind of arbitrary which mine an issue is posted to if it's a general issue.

**Comment by adf-ncgr** [comment]
I'm not sure LupinMine will want Google on board. Mr. Moore needs to operate without Big Brother watching.

**Comment by sammyjava** [comment]
Seriously? Why not? It's not really any different from traditional user creation. Or you mean no users at all?

**Comment by adf-ncgr** [comment]
not seriously.

**Comment by sammyjava** [comment]
Moved to mine-issues
